trahey_rest_main_annotations:
    resource: "@TraheyRestBundle/Controller/RESTController.php"
    prefix:   /%trahey_rest.api_prefix%
    type: annotation
trahey_rest_get_annotations:
    resource: "@TraheyRestBundle/Controller/GETController.php"
    prefix:   /%trahey_rest.api_prefix%
    type: annotation
trahey_rest_post_annotations:
    resource: "@TraheyRestBundle/Controller/POSTController.php"
    prefix:   /%trahey_rest.api_prefix%
    type: annotation
trahey_rest_put_annotations:
    resource: "@TraheyRestBundle/Controller/PUTController.php"
    prefix:   /%trahey_rest.api_prefix%
    type: annotation
trahey_rest_delete_annotations:
    resource: "@TraheyRestBundle/Controller/DELETEController.php"
    prefix:   /%trahey_rest.api_prefix%
    type: annotation
